---
- name: Install Nginx
  yum:
    update_cache: yes
    name: nginx
    state: latest

- name: Open http
  firewalld:
    zone: public
    service: http
    permanent: yes
    immediate: yes
    state: enabled
  notify:
    - restart nginx

- name: Open port
  firewalld:
    port: "{{ site_port }}/tcp"
    permanent: yes
    immediate: yes
    state: enabled
  notify:
    - restart nginx

- name: Open port SELinux
  seport:
    ports: "{{ site_port }}"
    proto: tcp
    setype: http_port_t
    state: present
  notify:
    - restart nginx

- name: Create website directory
  file: path="/var/www/{{ site_name }}" state=directory mode=0755

- name: Create nginx directory
  file: path="/etc/nginx" state=directory mode=0755
  
- name: Create nginx config directory
  file: path="/etc/nginx/conf.d" state=directory mode=0755

- name: Create nginx main config file
  template:
    src: "templates/nginx.conf"
    dest: "/etc/nginx/nginx.conf"
  notify:
    - restart nginx

- name: Create nginx vhost config file
  template:
    src: "templates/site.conf"
    dest: "/etc/nginx/conf.d/{{ site_name }}.conf"
  notify:
    - restart nginx

- name: Create index.html
  template:
    src: "templates/index.html"
    dest: "/var/www/{{ site_name }}/index.html"
  notify:
    - restart nginx
